name       : libusb
version    : 1.0.26
release    : 16
source     :
    - https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26.tar.bz2 : 12ce7a61fc9854d1d2a1ffe095f7b5fac19ddba095c259e6067a46500381b5a5
homepage   : https://libusb.info/
license    : LGPL-2.1-only
summary    : libusb (USB library)
component  : system.base
builddeps  :
    - pkgconfig32(libudev)
emul32     : yes
description: |
    libusb is a C library that gives applications easy access to USB devices on many different operating systems.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
