name       : libusb
version    : 1.0.24
release    : 13
source     :
    - https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2 : 7efd2685f7b327326dcfb85cee426d9b871fd70e22caa15bb68d595ce2a2b12a
homepage   : https://libusb.info/
license    : LGPL-2.1-only
summary    : libusb (USB library)
component  : system.base
builddeps  :
    - pkgconfig32(libudev)
emul32     : yes
description: |
    libusb is a C library that gives applications easy access to USB devices on many different operating systems.
setup      : |
    %patch -p1 < $pkgfiles/linux_usbfs-Fix-parsing-of-descriptors-for-multi-conf-devices.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
