name       : libusb
version    : 1.0.25
release    : 15
source     :
    - https://github.com/libusb/libusb/releases/download/v1.0.25/libusb-1.0.25.tar.bz2 : 8a28ef197a797ebac2702f095e81975e2b02b2eeff2774fa909c78a74ef50849
homepage   : https://libusb.info/
license    : LGPL-2.1-only
summary    : libusb (USB library)
component  : system.base
builddeps  :
    - pkgconfig32(libudev)
emul32     : yes
description: |
    libusb is a C library that gives applications easy access to USB devices on many different operating systems.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
