name        : libusb
version     : 1.0.19
release     : 4
source      :
    - http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-1.0.19/libusb-1.0.19.tar.bz2: 6c502c816002f90d4f76050a6429c3a7e0d84204222cbff2dce95dd773ba6840
homepage    : http://www.libusb.org
license     :
    - LGPL-2.0
summary     : libusb (USB library)
description : |
    libusb is a C library that gives applications easy access to USB devices on many different operating systems.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
