name       : libusb
version    : 1.0.21
release    : 8
source     :
    - http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-1.0.21/libusb-1.0.21.tar.bz2 : 7dce9cce9a81194b7065ee912bcd55eeffebab694ea403ffb91b67db66b1824b
homepage   : http://www.libusb.org
license    :
    - LGPL-2.0
summary    : libusb (USB library)
component  : system.base
builddeps  :
    - pkgconfig32(libudev)
emul32     : yes
description: |
    libusb is a C library that gives applications easy access to USB devices on many different operating systems.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make -j1
install    : |
    %make_install -j1
